### PR TITLE
feat: add `shutdown_all` for async and sync local kernels

### PR DESCRIPTION
**Pull request by oat-mirror**
-  add `shutdown_all`  for async and sync local kernels
- Align `hatch fmt` and `pre-commit` for line length settings.

### CODE REVIEW

**Comment by edwardzjl** [comment]
I have a small question, why don't use the default line length?

**Review by edwardzjl — APPROVED** [review]

**Comment by zTaoplus** [comment]
> I have a small question, why not using the default line length?

Due to the default `line-length` settings in pre-commit's [ruff format](https://docs.astral.sh/ruff/settings/#line-length) being different from those in [hatch's fmt](https://hatch.pypa.io/1.9/config/static-analysis/#default-settings), and since make lint in CI uses `hatch fmt`, this inconsistency will lead to CI failure. 
To resolve this issue, it is necessary to explicitly specify certain settings (such as line-length) in `pyproject.toml` to ensure consistent behavior between the two.

**Comment by edwardzjl** [comment]
Thank you for the explanation!

**Comment by edwardzjl** [comment]
Could you please take a look at the pending unittests?

**Comment by edwardzjl** [comment]
Please rebase this PR and let's see if the unittests hang.

**Comment by zTaoplus** [comment]
> Please rebase this PR and let's see if the unittests hang.

done

**Pull request merged**
